# Generated by Django 4.2.26 on 2025-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag', verbose_name='Теги'),
        ),
    ]
